config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :companies

  
  devise_for :users, controllers: {registrations: 'registrations'}
  
  root 'pages#home'
  
  get 'dashboard', to: "pages#dashboard"
    
    resources :trips, path_names: {edit: 'details' }
        
        
        resources :trips do
    resources :status_times
  end
  
  
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/page.rb
class Page < ActiveRecord::Base
    belongs_to :users
    
    
end

app/models/status_time.rb
class StatusTime < ActiveRecord::Base
  belongs_to :trip, inverse_of: :status_times
  belongs_to :user
  
validates :status, presence: true

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :status_times, inverse_of: :trip
  accepts_nested_attributes_for :status_times, allow_destroy: true
  has_many :status_times, inverse_of: :trip
  
 
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
        validates :time_zone, 
          inclusion: { 
           in: ActiveSupport::TimeZone.zones_map.keys 
       }        
         has_many :pages, inverse_of: :user       
         has_many :status_times, inverse_of: :user
         has_many :trips, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  around_filter :user_time_zone, if: :current_user

private

def user_time_zone(&block)
  Time.use_zone(current_user.time_zone, &block)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
    if current_user
  		redirect_to dashboard_path
  	end
  end

  def about
  end

  def contact
  end
  
  def dashboard
    #@user = User.find(params[:id])
    @user = current_user
    end


end      

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :password, :time_zone)
	end

	def account_update_params
		params.require(:user).permit(:email, 
		:password, 
		:current_password, 
		:first_name, 
		:last_name,
		:handle, 
		:telephone, 
		:time_zone
		)
	end

end

app/controllers/status_times_controller.rb
class StatusTimesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status_time, only: [:show, :edit, :update, :destroy]

#------------------------------------------------------------------------------ 

  def create
    @trip = Trip.find(params[:trip_id])
    @status_time = @trip.status_times.create(status_time_params)
    @status_time.user_id = current_user.id if current_user


      if @status_time.save
       redirect_to trip_path( @trip)
        flash[:success] = 'Your driving status has been updated.'
      else
       redirect_to trip_path( @trip), notice: 
        flash[:danger] = "what the hell are you trying to do!" 
      end
    end


#------------------------------------------------------------------------------ 

  def destroy
    @status_time.destroy
    respond_to do |format|
      format.html { redirect_to status_times_url, notice: 'Status time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
#------------------------------------------------------------------------------ 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_time
      @status_time = StatusTime.find(params[:id])
    end

#------------------------------------------------------------------------------ 

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_time_params
      params.require(:status_time).permit(:status, :location, :notes, :time, :trip_id, :user_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

#-------------------------------------------------------------------------------

  def index
   @trips = current_user.trips
   #@trips = Trip.all
  end

#-------------------------------------------------------------------------------

  def show
    @status_times = @trip.status_times.all
    #@status_times = @trip.current_user.status_times
  end

#-------------------------------------------------------------------------------

  def new
    @trip = Trip.new
    @trip.status_times.new
  end

#-------------------------------------------------------------------------------

  def edit # name change in routes to "detials'
    @status_times = @trip.status_times(params[:id])
    @trip = current_user.trips(params[:id])
    @tripdate = current_user.trips.find(params[:id])
   
  end

#-------------------------------------------------------------------------------

 def create
    
    @trip = current_user.trips.new(trip_params)
    #@trip = Trip.find(params[:trip_id])
    #@status_time = @trip.status_times.create(status_time_params)
   # @status_time.user_id = current_user.id if current_user

 
    if @trip.save
       redirect_to @trip, notice: 'Trip was successfully created.' 
    
    else
      render :new 
    
    end
  end

#-------------------------------------------------------------------------------

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

#-------------------------------------------------------------------------------

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
#-------------------------------------------------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end
    
#-------------------------------------------------------------------------------

    def trip_params
      params.require(:trip).permit(
        :user_id, :created_at,
          status_times_attributes: [
            :user_id, 
            :_destroy,
            :status,
            :notes,
            :location,
            :created_at,
            :updated_at,
            :trip_id,
            :id
            ]
          )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
    
end

app/helpers/status_times_helper.rb
module StatusTimesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %>
<button class="close" data-dismiss="alert">x</button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright Fr8Quote Inc.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li>More Here</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to image_tag("fq.png"), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
 <ul class="nav navbar-nav navbar-right">

          <% if current_user %>
      
      
      <li><%= link_to "Trips", trips_path %></li>
      <li><%=link_to "My Dashboard", dashboard_path(current_user.id)%></li>
      

      <!-- Drop Down-->
 
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Account Settings", edit_user_registration_path %></li>
            
            <li><%=link_to "Contact Us", contact_path %></li>
            
            <li><%=link_to "Close Data Session", destroy_user_session_path, method: :delete %></li>
      <%else%>

    <li><%=link_to "Contact Us", contact_path %></li>
    <li>  <%=link_to "About Us", about_path %></li>
    <li><%=link_to "Login for Data", new_user_session_path %></li>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
  
 <%end%>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/nav' %>
 
    <div class="container">
        
 <%= render 'layouts/flash' %>
           <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>All About Us</h1>
<p>The story of how we work and why we are the best!</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contacts</h1>
<p>A list of contact info</p>

app/views/pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>


<h4><%= .@user.handle %>'s Dashboard</h4> 
<p>stuff for dashboard

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1>Welcome To Chesnowitz Media!</h1>
<h2>

<a href="#">Chezzie's Awsome Apps!</a>

</h2>
<%= link_to "Sign up!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.ico"),
'http://chezzyk.com/' %>

app/views/shared/_status_views.html.erb
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
      <th>Status</th>
      <th>Service Time</th>
      <th>Notes</th>
      <th>Location</th>
      <th>Trip ID</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_times.each do |status_time| %>
      <tr>
        <td><%= status_time.status %></td>
        <td><%= status_time.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %></td>
        <td><%= status_time.notes %></td>
        <td><%= status_time.location %></td>
        <td><%= status_time.trip_id %></td>
        
        
    </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/status_times/_form.html.erb
<%= simple_form_for(@status_time) do |f| %>
 

    <%= f.label :status %><br>
    <%= f.label :location %><br>
    <%= f.label :notes %><br>
    <%= f.label :user_id %><br>
    <%= f.label :trip_id %><br>
    <%= f.submit %>

<% end %>

app/views/status_times/edit.html.erb
<h1>Editing Status Time</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_time %> |
<%= link_to 'Back', status_times_path %>

app/views/status_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Status Times</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Location</th>
      <th>Notes</th>
      <th>User</th>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_times.each do |status_time| %>
      <tr>
        <td><%= status_time.status %></td>
        <td><%= status_time.location %></td>
        <td><%= status_time.notes %></td>
        <td><%= status_time.user %></td>
        <td><%= status_time.trip %></td>
        <td><%= link_to 'Show', status_time %></td>
        <td><%= link_to 'Edit', edit_status_time_path(status_time) %></td>
        <td><%= link_to 'Destroy', status_time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status time', new_status_time_path %>

app/views/status_times/new.html.erb
<h1>New Status Time</h1>

<%= render 'form' %>

<%= link_to 'Back', status_times_path %>

app/views/status_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @status_time.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @status_time.location %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @status_time.notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @status_time.user %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @status_time.trip %>
</p>

<%= link_to 'Edit', edit_status_time_path(@status_time) %> |
<%= link_to 'Back', status_times_path %>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
 
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h4>Record created on: <%= @tripdate.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %> 
 </h4>

<%= render partial: 'shared/status_views' %>



<%= link_to 'Back', trips_path, class: 'btn btn-mini btn-success' %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
      <th>Trip Date</th>
      <th>Service Time</th>
      <th>Notes</th>
      <th>Location</th>
      <th>User ID</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %></td> 
        <td></td>
        
        <td><%= link_to 'Details', edit_trip_path(trip), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
   </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<!-------------------------Status Form----------------------------------->

<%= simple_form_for([@trip, @trip.status_times.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     
    <%= f.input :status, collection: [ "On Duty Not Driving", "Driving", 
                    "Off Duty", "In Sleeper"], prompt: "Select Status"  %>
    <%= f.input :notes %>
    <%= f.input :location %>
   
    
   
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-mini btn-success' %>
  </div>
<% end %>

<!--------------------End Status Form----------------------------------->
<%= render partial: 'shared/status_views' %>